config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'    
  devise_for :users
  resources :links, only: [:new, :index, :create]

  get '/:slug' => 'links#show'
  get '/links/detail/:slug' => 'links#detail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/use_case/create_link.rb
module UseCase
  class CreateLink
    attr_reader :given_url, :user_id

    def initialize(args)
      @given_url = args["given_url"]
      @user_id = args["user_id"]
    end

    def call
      link = nil
      while link.nil?
        link = create_link
      end
      link
    end

    private

    def create_link
      begin
        link = Link.create(slug: generate_slug, given_url: given_url, user_id: user_id)
        write_to_cache(link)
      rescue
        link = nil
      end
      link
    end

    def write_to_cache link
      Rails.logger.info "CacheStore::Key=#{link.slug} started"
      response = Rails.cache.write(link.slug, link, expires_in: 5.hours)
      Rails.logger.info "Cache::Key=#{link.slug} finished status=#{response}"
    end

    def generate_slug
      SecureRandom.hex(10)
    end
  end
end

app/models/use_case/get_link.rb
module UseCase
  class GetLink
    attr_reader :slug
    
    def initialize(slug:)
      @slug = slug
    end

    def call
      link = find_in_cache
      link = find_in_db if link.nil?
      update_count link unless link.nil?
      link
    end

    private 

    def find_in_cache
      Rails.logger.info "CacheFetch::Key=#{slug} started"
      link = Rails.cache.read(slug)
      Rails.logger.info "CacheFetch::Key=#{slug} finished response = #{link}"
      link
    end
    
    def find_in_db
      link = Link.find_by(slug: slug)
      store_in_cache link unless link.nil?
      link
    end

    def store_in_cache link
      Rails.logger.info "CacheStore::Key=#{link.slug} started"
      response = Rails.cache.write(link.slug, link, expires_in: 5.hours)
      Rails.logger.info "Cache::Key=#{link.slug} finished status=#{response}"
    end

    def update_count link
      link.increment!(:use_count)
    end
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :detail]
  before_action :authenticate_user!, except: [:show, :detail]



  # GET /links
  # GET /links.json
  def index
    @host_name = request.server_name
    @links = Link.order(:created_at).paginate(page: params[:page], per_page: 5)
  end

  def new
    @link = Link.new
    respond_to do |format|
      format.js
    end
  end

  def detail
    if @link
      render json: { status: :ok, data: @link }
    else
      render json: { status: :not_found }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    if @link
      redirect_to @link.given_url
    else
      redirect_to root_url, alert: 'No matching url found.'
    end
  end


  # POST /links
  # POST /links.json
  def create
    @link = UseCase::CreateLink.new(link_params).call

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.

    def set_link
      @link = UseCase::GetLink.new(slug: params[:slug]).call
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:given_url).to_h.merge!(user_id: current_user.id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-light navbar-light">

    <!-- Links -->
    <a class="navbar-brand" href="#">Logo</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
    </ul>

    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">

      <ul class="navbar-nav">
       <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= current_user.email %></a>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
      </li>
      <% else %>

      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="container">
  <% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
      <strong>Warning!</strong><%= alert %>
    </div>
    <% end %>
    <% if notice %>
    <div class="alert alert-info" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
  </html>

app/views/links/_form.html.erb
<%= bootstrap_form_for(@link, local: true) do |form| %>
<% if @link.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

  <ul>
    <% @link.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<%= form.text_field :given_url, required: true, help: 'https://www.moneysmart.sg/' %>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/links/_modal.html.erb
<div class="modal fade" id="form_modal" role="modal">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
        <!-- <h4 class="modal-title">Modal Header</h4> -->
        <h4 class="modal-title text-center"><%= action_name.capitalize %> Link</h4>
      </div>
      <div class="modal-body">
        <%= render 'links/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/links/index.html.erb
<div id="myModal"></div>
<div class="row">
  <%= link_to "New Link", new_link_path, remote: true, class: "btn btn-secondary float-right" %>
</div>

  <h2> Links </h2>
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>Given URL</th>
        <th>Slug</th>
        <th>Use Count</th>
        <th>Shortend URL</th>
      </tr>
    </thead>
    <tbody>
      <tbody>
        <% @links.each do |link| %>
        <tr>
          <td><%= truncate(link.given_url, length: 60) %></td>
          <td><%= link.slug %></td>
          <td><%= link.use_count %></td>
          <td><%= link_to "#{@host_name}/#{link.slug}","/#{link.slug}" , target: '_blank' %></td>
        </tr>
        <% end %>
      </tbody>
    </tbody>
  </table>
  
  <%= will_paginate(@links, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/links/new.html.erb
<!-- <h1>New Link</h1> -->

<%#= render 'form', link: @link %>

<%#= link_to 'Back', links_path %>

$("#myModal").html("<%= j render "modal"%>");
$('#form_modal').modal('show'); 

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given url:</strong>
  <%= @link.given_url %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @link.slug %>
</p>

<p>
  <strong>Use count:</strong>
  <%= @link.use_count %>
</p>

<%#= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>